language: php
php:
  - 5.4
  - 5.5

before_script:
  - composer install
  - composer require satooshi/php-coveralls:~0.6@stable  - mkdir -p build/logs
  - mkdir -p build/logs

script:
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml test/

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'