language: php
php:
  - 5.4
  - 5.5

before_script:
  - mkdir -p build/logs
  - composer require satooshi/php-coveralls: "dev-master"
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml test/

after_success:
 - php vendor/bin/coveralls -v